### ISSUE TITLE
Fill naming table 

### ISSUE THREAD

**Issue by albertolluch** [pSpaces/dotSpace#9]
Column C# to be filled here:

https://github.com/pSpaces/Programming-with-Spaces/blob/master/naming.md

**Comment by sequenze** [comment]
I dont have write permissions....

**Comment by sequenze** [comment]
This has been completed.

**Comment by sequenze** [comment]
Hi Alberto

An error has been reported: https://github.com/pSpaces/dotSpace/issues/10

I have implemented a fix just now. It seems to be working but……
I don’t have the time to repeatedly keep testing, so as it is right not dotSpace is working without the fix because it is not critical.

Would you prefer that I publish the fix, tested but not thoroughly, or do you want me to wait until after the 3 week semester?

Best
Shane

**Comment by albertolluch** [comment]
I replied by email, sorry. In any case, I would go for implementing `delSpace` and publishing it. Btw. jSpace has a similar issue.
